# Generated by Django 5.0.2 on 2025-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAidRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('CRIMINAL', 'Criminal Defense'), ('FAMILY', 'Family Law'), ('IMMIGRATION', 'Immigration'), ('HOUSING', 'Housing'), ('EMPLOYMENT', 'Employment'), ('CONSUMER', 'Consumer Rights'), ('CIVIL', 'Civil Rights'), ('OTHER', 'Other')], max_length=20)),
                ('urgency_level', models.CharField(choices=[('HIGH', 'High - Immediate attention required'), ('MEDIUM', 'Medium - Within a week'), ('LOW', 'Low - General consultation')], max_length=10)),
                ('description', models.TextField()),
                ('contact_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
    ]
